### ISSUE TITLE
[Question] How to reject a Promise?

### ISSUE THREAD

**Issue by ishan1608** [miguelgrinberg/promisio#3]
### Discussed in https://github.com/miguelgrinberg/promisio/discussions/2

<div type='discussions-op-text'>

<sup>Originally posted by **ishan1608** April 16, 2022</sup>
Hey Miguel Grinberg,

How do I reject a promise?
I have this scenario where I have to make two HTTP calls and one call to AWS Cognito.
Calling them serially is working at the moment. But I want to call them in parallel as they are not dependent on each other.
I couldn't figure out how to `reject` from a function which is decorated with `@promisify`

So, I tried using the `Promise` class itself.
I am going to provide my attempt and the error that I am getting.
Any help would be appreciated.

Code:
```python
import asyncio
from asyncio.exceptions import CancelledError, InvalidStateError
from datetime import datetime

from promisio import promisify, Promise


def task_a(arg1, arg2):
    def _task_a(resolve, reject):
        val = f'task a {arg1} : {arg2} -- {datetime.now()}'
        print(val)
        some_condition = 5
        if some_condition == 5:
            return reject(BaseException('Failing task a'))
        return resolve(val)

    return Promise(f=_task_a)


@promisify
async def task_b(arg1, arg2):
    await asyncio.sleep(2.5)
    val = f'task b {arg1} : {arg2} -- {datetime.now()}'
    print(val)
    return val


@promisify
async def task_c(arg1, arg2):
    await asyncio.sleep(3)
    val = f'task c {arg1} : {arg2} -- {datetime.now()}'
    print(val)
    return val


async def main():
    pr_b = task_b(2, 2)
    print(pr_b)

    try:
        pr_a = task_a(1, 1)
        print(pr_a)
    except InvalidStateError as error:
        print('task_a threw error')
        print(error)
    except CancelledError as error:
        print('task_a threw error')
        print(error)
    except BaseException as error:
        print('task_a threw error')
        print(error)

    pr_c = task_c(3, 3)
    print(pr_c)
    # await pr_a
    # await pr_b
    # await pr_c
    pr_all = Promise.all([pr_a, pr_b, pr_c])
    pr_all = pr_all.then(on_resolved=lambda x: print(f'All resolved {x}'), on_rejected=lambda x: print(f'Rejected {x}'))
    await pr_all


if __name__ == '__main__':
    asyncio.run(main())

```

Error:
```python
<promisio.TaskPromise object at 0x7fb8519f0250>
task a 1 : 1 -- 2022-04-16 09:55:45.791987
<promisio.Promise object at 0x7fb8519f02e0>
<promisio.TaskPromise object at 0x7fb8519f0340>
Rejected Failing task a
Future exception was never retrieved
future: <Future finished exception=InvalidStateError('invalid state')>
Traceback (most recent call last):
  File "/home/ishan/.venv/heka/lib/python3.8/site-packages/promisio/__init__.py", line 272, in _handle_done
    result = future.result()
  File "/home/ishan/.venv/heka/lib/python3.8/site-packages/promisio/__init__.py", line 272, in _handle_done
    result = future.result()
  File "/home/ishan/.venv/heka/lib/python3.8/site-packages/promisio/__init__.py", line 272, in _handle_done
    result = future.result()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ishan/.venv/heka/lib/python3.8/site-packages/promisio/__init__.py", line 256, in _handle_callback
    callback_result = callback(result)
  File "/home/ishan/.venv/heka/lib/python3.8/site-packages/promisio/__init__.py", line 250, in _reject
    self.future.set_exception(error)
asyncio.exceptions.InvalidStateError: invalid state
Future exception was never retrieved
future: <Future finished exception=InvalidStateError('invalid state')>
Traceback (most recent call last):
  File "/home/ishan/.venv/heka/lib/python3.8/site-packages/promisio/__init__.py", line 272, in _handle_done
    result = future.result()
  File "/home/ishan/.venv/heka/lib/python3.8/site-packages/promisio/__init__.py", line 272, in _handle_done
    result = future.result()
  File "/home/ishan/.venv/heka/lib/python3.8/site-packages/promisio/__init__.py", line 272, in _handle_done
    result = future.result()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ishan/.venv/heka/lib/python3.8/site-packages/promisio/__init__.py", line 256, in _handle_callback
    callback_result = callback(result)
  File "/home/ishan/.venv/heka/lib/python3.8/site-packages/promisio/__init__.py", line 250, in _reject
    self.future.set_exception(error)
asyncio.exceptions.InvalidStateError: invalid state

```</div>

**Comment by miguelgrinberg** [comment]
What is the purpose of writing the same report first as a discussion and then as an issue?
